### ISSUE TITLE
Bazel build issue

### ISSUE THREAD

**Issue by ghost** [j2kun/mlir-tutorial#44] opened 2024-09-28 09:35 UTC
I am new to use Bazel universe,

After cloning the repo, I tried to run: **bazel build ...:all**

But I got the following error:

ERROR: Skipping '...:all': error loading package under directory '': error loading package 'externals/llvm-project/utils/bazel/llvm-project-overlay/mlir/unittests': Every .bzl file must have a corresponding package, but '//mlir:tblgen.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.

**Comment by j2kun** [comment] 2024-09-29 03:38
I think the most recent push of the PDLL article might have landed the tutorial at a bad upstream LLVM commit hash. I cannot reproduce this myself but I see a different, perhaps related issue. I will try bumping it to a more recent commit and see if that resolves the issue.

**Comment by j2kun** [comment] 2024-09-29 03:46
ah I see the problem. The CMake build added the `externals` directory, which is conflicting with the glob in `bazel build ...:all` because the external LLVM from that directory includes bazel files.

You can get around this by just building a specific target, either `bazel build //tools:tutorial-opt` for the main binary, or else `bazel test //tests/...:all` for tests.

**Comment by j2kun** [comment] 2024-09-29 04:05
I found a slightly better fix: adding `--deleted_packages=externals` to `.bazelrc`. Try updating to the latest commit of this repository and running `bazel build ...:all` again.

**Closed** 2024-12-12 17:47 UTC
